
package com.coverity.ws.v9;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ConfigurationServiceService", targetNamespace = "http://ws.coverity.com/v9", wsdlLocation = "http://igor.internal.synopsys.com:8871/ws/v9/configurationservice?wsdl")
public class ConfigurationServiceService
    extends Service
{

    private final static URL CONFIGURATIONSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONFIGURATIONSERVICESERVICE_EXCEPTION;
    private final static QName CONFIGURATIONSERVICESERVICE_QNAME = new QName("http://ws.coverity.com/v9", "ConfigurationServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://igor.internal.synopsys.com:8871/ws/v9/configurationservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONFIGURATIONSERVICESERVICE_WSDL_LOCATION = url;
        CONFIGURATIONSERVICESERVICE_EXCEPTION = e;
    }

    public ConfigurationServiceService() {
        super(__getWsdlLocation(), CONFIGURATIONSERVICESERVICE_QNAME);
    }

    public ConfigurationServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ConfigurationService
     */
    @WebEndpoint(name = "ConfigurationServicePort")
    public ConfigurationService getConfigurationServicePort() {
        return super.getPort(new QName("http://ws.coverity.com/v9", "ConfigurationServicePort"), ConfigurationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfigurationService
     */
    @WebEndpoint(name = "ConfigurationServicePort")
    public ConfigurationService getConfigurationServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.coverity.com/v9", "ConfigurationServicePort"), ConfigurationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONFIGURATIONSERVICESERVICE_EXCEPTION!= null) {
            throw CONFIGURATIONSERVICESERVICE_EXCEPTION;
        }
        return CONFIGURATIONSERVICESERVICE_WSDL_LOCATION;
    }

}
